server {
    listen 80;

    server_name localhost;

    # Rediriger les requêtes API vers l'API backend
    location /api/ {
        proxy_pass http://192.168.88.46:3000/;  # Rediriger vers l'API backend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Servir l'application Angular
    location / {
        root /usr/share/nginx/html;  # Le dossier contenant l'application Angular
        try_files $uri $uri/ /index.html;  # Pour gérer les routes Angular
    }

    # Gérer les erreurs
    error_page  405     =200 $uri;
}